linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
    - gci
    - staticcheck
    - paralleltest
    - ineffassign

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/sagernet/)
      - default

run:
  go: "1.23"